name = "my-app-hono"
main = "src/index.ts"
compatibility_date = "2024-11-21"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
tiktok_v2_key = "*****************************"
tiktok_v2_url = ""*****************************""

# [[r2_buckets]]
binding = "******"
bucket_name = ""******""

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
